### ISSUE TITLE
Issue Directory

### ISSUE THREAD

**Issue by Vito711** [paulschwoerer/leafplayer#15]
Hi, I have installed correctly the server with Docker, 
I created correctly a user , but i have an issue when I stat a scan when i start it finish after some seconds, and no music appear on the website, I set as folder the patch "/media_data/ and /home/ubuntu/leafplayer/music/" but nothing appears, 
Why?

**Comment by paulschwoerer** [comment]
Hi Vito,
I assume you have done the following:

1. mounted your music folder into the docker container (-v /path/to/your/music:/music:ro)
2. added the mounted folder (... library:dir --add /music)
3. ran the scan (... library:scan)

Is that correct? 
Also, do the logs of your leafplayer container show anything out of order?

**Comment by Vito711** [comment]
Yes, I have done it, but there is no possibility, to mount a folder in a different path?

**Comment by paulschwoerer** [comment]
It is possible to mount a folder in a different path, as long as you use the same path when adding a library folder. For example, if your music is stored in `/home/ubuntu/leafplayer/music`, you could mount that to `/media_data` inside the container 

```sh
# some arguments have been omitted for clarity

docker run  -v "/home/ubuntu/leafplayer/music:/media_data:ro" paulschwoerer/leafplayer
```

Now you can add the `/media_data` folder as a library folder

```sh
docker exec -it node main.js library:dir --add /media_data leafplayer
```

After scanning, your music should be available in the web interface.

I hope, I understood your issue correctly. Let me know if that clears things up.
